//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingCourseProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OWNER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OWNER()
        {
            this.VEHICLE = new HashSet<VEHICLE>();
            this.PASS = new HashSet<PASS>();
            this.PLACE = new HashSet<PLACE>();
        }
    
        public int ID_Owner { get; set; }
        public string Full_name { get; set; }
        public string Adress { get; set; }
        public string Tel_number { get; set; }
        public Nullable<decimal> Debt { get; set; }
        public string Password { get; set; }
        public byte[] IMG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VEHICLE> VEHICLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PASS> PASS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLACE> PLACE { get; set; }
    }
}
