//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingCourseProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLACE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLACE()
        {
            this.OWNER = new HashSet<OWNER>();
        }
    
        public int ID_Place { get; set; }
        public Nullable<bool> Special_place { get; set; }
        public Nullable<bool> Occupation { get; set; }
        public Nullable<int> ID_Vehicle { get; set; }
        public Nullable<int> ID_Owner { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OWNER> OWNER { get; set; }
        public virtual OWNER OWNER1 { get; set; }
        public virtual VEHICLE VEHICLE { get; set; }
    }
}
