//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingCourseProject.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VEHICLE()
        {
            this.OWNER = new HashSet<OWNER>();
            this.PLACE = new HashSet<PLACE>();
        }
    
        public int ID_Vehicle { get; set; }
        public string Vehicle_name { get; set; }
        public string Vehicle_number { get; set; }
        public string Color { get; set; }
        public Nullable<bool> Special_vehicle { get; set; }
        public Nullable<int> ID_Owner { get; set; }
        public byte[] IMG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OWNER> OWNER { get; set; }
        public virtual OWNER OWNER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLACE> PLACE { get; set; }
    }
}
